### PR TITLE
Vue rewrite

### LINKED ISSUE #103: Hiding display keeps splitter visible
If hiding the display, for example via compilation, the splitter between the compile output and the display remains visible and interactable despite the display not working.

### LINKED ISSUE #104: Tooltip visuals are buggy when clicking multiple times
The tooltip on share is coded to hide 3s after appearing, but if you click it again this timer isn't reset so it will disappear faster than normal, and then if you click it again it will appear and disappear quickly.

### LINKED ISSUE #105: Performance overlay disappears until resize if window is resized during compilation

### PR DESCRIPTION
**Pull request by Devon7925**
Fixes #103
Fixes #104
Fixes #105

Deploy: https://devon7925.github.io/slang-playground/

Other changes:
* Updated `README`, should be easier for people to follow build instructions now
* Removed `RequireJS` dependency
* Changed library from `split-grid` to `splitpanes` to work better with Vue and have a cleaner implementation

Loading time is slightly worse on slow connection 14s vs 12s but has a slightly faster time to first render.
Loading time is slightly faster with caching and fast connection 1.6s vs 2s.

Hot reload time is faster due to using Vite, and loading times should scale better since code is minified.

Apart from fixes behavior should be unchanged.

### CODE REVIEW

**Comment by csyonghe** [comment]
I tried this from iOS Safari, and it seems the reflection panel can't be scrolled.

**Comment by csyonghe** [comment]
Apart from that, everything seems to be working well. I really like how the build dependency step is cleaned up and you can just download the built binaries from actions!

**Comment by Devon7925** [comment]
I fixed the reflection scrolling issue, updated code is on my deploy.

**Comment by csyonghe** [comment]
There is another issue: popup tooltip panels from the Monaco editor is clipped by its client rect:
image

This issue is worked around in the original implementation by making sure the editor and all its parent containers have `overflow:visible` style, and only make them `overflow:hidden` during resize.

File: src/App.vue [hunk 1]
```diff
@@ -0,0 +1,577 @@
...
+
+function logError(message: string) {
+    diagnosticsArea.value?.appendEditorValue(message + "\n", true);
+}
+</script>
+
+<template>
+    <Tooltip ref="tooltip"></Tooltip>
+    <Transition>
+        <div id="loading-screen" v-if="!initialized">
```
Comment (csyonghe) [inline src/App.vue:421]: This is also defined in index.html, do we need both?

**Review by csyonghe — APPROVED** [review]
I am not an expert on Vue to review every line of change here in detail, but the result looks good and I am OK with merging as is.

File: src/App.vue (hunk 1 above)
Comment (Devon7925) [reply src/App.vue:421]: The definition in index.html gets overridden. It's used to give users an earlier first render before the Vue code loads.

Comment (csyonghe) [reply src/App.vue:421]: I see. Maybe we can separate it out to slits own file that gets included from here and the vue template?
